export const LETTERS = [
  [
    { letter: "q" },
    { letter: "w" },
    { letter: "e" },
    { letter: "r" },
    { letter: "t" },
    { letter: "y" },
    { letter: "u" },
    { letter: "i" },
    { letter: "o" },
    { letter: "p" },
  ],
  [
    { type: "half" },
    { letter: "a" },
    { letter: "s" },
    { letter: "d" },
    { letter: "f" },
    { letter: "g" },
    { letter: "h" },
    { letter: "j" },
    { letter: "k" },
    { letter: "l" },
    { type: "half" },
  ],
  [
    { letter: "z" },
    { letter: "x" },
    { letter: "c" },
    { letter: "v" },
    { letter: "b" },
    { letter: "n" },
    { letter: "m" },
    { type: "delete" },
  ],
];
